---
title: "Model Comparison"
author: "Tom & Will"
date: "3/28/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(baseballr)
library(janitor)
library(here)
library(tidyverse)
library(gtsummary)
library(here)
source(here::here("R", "scrape_bref.R"))
knitr::opts_chunk$set(echo = FALSE)
```

```{r data, include=FALSE}

last_year <- 2021
this_year <- 2022
games_this_year <- 162
last_ten_years <- c((last_year-9):last_year)

team_abbreviation_map <-
  here::here("in", "team_abbrevation_map.csv") %>% 
  readr::read_csv() %>% 
  janitor::clean_names()

batting_historic_raw <-
  last_ten_years %>% 
  map(team_batting) %>% 
  bind_rows() %>% 
  filter(!tm %in% c('LgAvg','LgTot','League Average')) %>% 
  janitor::clean_names()

batting_against_raw <- 
  last_ten_years %>% 
  map(team_batting_against) %>% 
  bind_rows() %>% 
  filter(!tm %in% c('LgAvg','LgTot','League Average')) %>% 
  janitor::clean_names()

batting_historic <-
  batting_historic_raw %>% 
  rename(team_name = tm) %>% 
  left_join(team_abbreviation_map) %>% 
  rename(ops_plus = ops_2) %>% 
  select(year, league, tm, number_bat:lob) %>% 
  mutate(across(!c(tm, league), as.numeric)) %>% 
  mutate(iso = slg - ba,
         hits_per_run = h / r,
         br_a = h + bb + hbp -(.5*ibb) - hr,
         br_b = 1.1 * ((1.4*slg*ab) - (.6*h) - (3*hr) - (.1*(bb+hbp-ibb)) + (.9*(sb-cs-gdp))),
         br_c = pa - bb - sf - sh - hbp - h + cs + gdp,
         br_raw = br_a*br_b/(br_b+br_c)+hr)

batting_against_historic <-
  batting_against_raw %>% 
  rename(team_name = tm) %>% 
  left_join(team_abbreviation_map) %>% 
  select(year, league, tm, ra_g:roe) %>% 
  mutate(across(!c(tm, league), as.numeric)) %>% 
  mutate(iso = slg - ba,
         hits_per_run = h / r,
         br_a = h + bb + hbp -(.5*ibb) - hr,
         br_b = 1.1 * ((1.4*slg*ab) - (.6*h) - (3*hr) - (.1*(bb+hbp-ibb)) + (.9*(sb-cs-gdp))),
         br_c = pa - bb - sf - sh - hbp - h + cs + gdp,
         br_raw = br_a*br_b/(br_b+br_c)+hr)

br_adjustments <-
  batting_historic %>% 
  group_by(year, league) %>% 
  summarize(r = sum(r),
            br_raw = sum(br_raw)) %>% 
  mutate(adj = r / br_raw) %>% 
  select(-r, -br_raw)

batting_historic <-
  batting_historic %>% 
  left_join(br_adjustments) %>% 
  mutate(base_runs = br_raw * adj * (162/g)) %>% 
  select(-c(br_a:adj))

batting_against_historic <-
  batting_against_historic %>% 
  left_join(br_adjustments) %>% 
  mutate(base_runs = br_raw * adj * (162/g)) %>% 
  select(-c(br_a:adj))

```


### Hits Per Run Model

```{r Hits Per Run, echo=FALSE}

batting_historic %>% 
  lm(hits_per_run ~ obp + slg + iso, .) %>% 
  tbl_regression() %>% 
  add_glance_table(include = c(nobs, r.squared, AIC)) 

```

### Hits Per Run Against Model
```{r Hits Per Run Against, echo=FALSE}

batting_against_historic %>% 
  lm(hits_per_run ~ obp + slg + iso, .) %>% 
  tbl_regression() %>% 
  add_glance_table(include = c(nobs, r.squared, AIC)) 
```
  