---
title: "Pre-season POC"
author: "Tom & Will"
date: "2/6/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(xml2)
library(plotly)
library(tidyverse)
library(baseballr)
library(janitor)
library(here)
source(here::here("R", "scrape_bref.R"))
```

```{r constants_and_functions}
last_year <- 2021
this_year <- 2022
games_this_year <- 162
ex <- 1.83
last_ten_years <- c((last_year-9):last_year)

apply_adjustments <- function(df1, df2) {
  df1 %>% 
    full_join(df2, by = "tm") %>% 
    mutate(r = r.x + r.y,
           ra = ra.x + ra.y) %>% 
    select(tm, r, ra)
}

```

```{r raw_inputs} 

team_abbreviation_map <-
  here::here("in", "team_abbrevation_map.csv") %>% 
  readr::read_csv() %>% 
  janitor::clean_names()

standings_last_year_raw <- 
  standings_expanded(last_year) %>% 
  filter(tm != 'Avg') %>% 
  janitor::clean_names() 

batting_historic_raw <-
  last_ten_years %>% 
  map(team_batting) %>% 
  bind_rows() %>% 
  filter(!tm %in% c('LgAvg','LgTot','League Average')) %>% 
  janitor::clean_names()

# https://www.fangraphs.com/leaders.aspx?pos=all&stats=bat&lg=all&qual=0&type=8&season=2021&month=0&season1=2021&ind=0&team=0,ts&rost=&age=&filter=&players=0
fangraphs_batting_last_year <-
  read_csv(here::here("in","last_year_batting_results.csv")) %>% 
  janitor::clean_names()

# https://www.fangraphs.com/leaders.aspx?pos=all&stats=pit&lg=all&qual=0&type=8&season=2021&month=0&season1=2021&ind=0&team=0,ts&rost=0&age=0&filter=&players=0&startdate=&enddate=
fangraphs_pitching_last_year <-
  read_csv(here::here("in","last_year_pitching_results.csv")) %>% 
  janitor::clean_names()

batting_against_raw <- 
  last_ten_years %>% 
  map(team_batting_against) %>% 
  bind_rows() %>% 
  filter(!tm %in% c('LgAvg','LgTot','League Average')) %>% 
  janitor::clean_names()

# https://www.fangraphs.com/projections.aspx?pos=all&stats=bat&type=fangraphsdc
batting_projections_this_year <-
  here::here("in", "this_year_batting_projections.csv") %>%
  readr::read_csv() %>% 
  janitor::clean_names() %>% 
  dplyr::filter(!is.na(team)) %>% 
  group_by(team) %>% 
  summarize(war_proj = sum(war)) %>% 
  rename(tm=team) %>% 
  select(tm, war_proj)

# https://www.fangraphs.com/projections.aspx?pos=all&stats=pit&type=fangraphsdc&team=0&lg=all&players=0
pitching_projections_this_year <-
  here::here("in", "this_year_pitching_projections.csv") %>%
  readr::read_csv() %>% 
  janitor::clean_names() %>% 
  dplyr::filter(!is.na(team)) %>% 
  group_by(team) %>% 
  summarize(war_proj = sum(war)) %>% 
  rename(tm=team) %>% 
  select(tm, war_proj)

fangraphs_projections_url <- 
  "https://www.fangraphs.com/depthcharts.aspx?position=Standings"
  
fangraphs_projections <-
  fangraphs_projections_url %>%
  read_html() %>%
  html_nodes("table") %>%
  html_table() %>%
  .[[8]] %>%
  as_tibble() %>%
  select(1, 16:21) %>%
  janitor::row_to_names(2) %>%
  janitor::clean_names() %>% 
  left_join(team_abbreviation_map) %>% 
  select(tm, w:ra_g) %>% 
  rename(wp = w_percent) %>% 
  mutate(across(-tm, as.numeric))

win_total_odds_raw <-
  "https://www.thelines.com/odds/mlb/win-totals/" %>% 
  read_html() %>%
  html_nodes("table") %>% 
  html_table(fill = TRUE) %>% 
  .[[2]] %>% 
  as_tibble() %>% 
  select(1:2) 
colnames(win_total_odds_raw) <- c("team_name", "o_u_wins_this_year")

```


```{r prep inputs, calculate base runs}

standings_last_year <- 
  standings_last_year_raw %>% 
  filter(tm != 'Average') %>% 
  rename(team_name = tm) %>% 
  left_join(team_abbreviation_map) %>% 
  select(year, tm, w:w_l_percent, r, ra) %>% 
  mutate(g = w+l,
         r = as.numeric(r),
         ra = as.numeric(ra)) %>% 
  rename(r_g = r,
         ra_g = ra)

batting_historic <-
  batting_historic_raw %>% 
  rename(team_name = tm) %>% 
  left_join(team_abbreviation_map) %>% 
  rename(ops_plus = ops_2) %>% 
  select(year, league, tm, number_bat:lob) %>% 
  mutate(across(!c(tm, league), as.numeric)) %>% 
  mutate(iso = slg - ba,
         hits_per_run = h / r,
         br_a = h + bb + hbp -(.5*ibb) - hr,
         br_b = 1.1 * ((1.4*slg*ab) - (.6*h) - (3*hr) - (.1*(bb+hbp-ibb)) + (.9*(sb-cs-gdp))),
         br_c = pa - bb - sf - sh - hbp - h + cs + gdp,
         br_raw = br_a*br_b/(br_b+br_c)+hr)

batting_against_historic <-
  batting_against_raw %>% 
  rename(team_name = tm) %>% 
  left_join(team_abbreviation_map) %>% 
  select(year, league, tm, ra_g:roe) %>% 
  mutate(across(!c(tm, league), as.numeric)) %>% 
  mutate(iso = slg - ba,
         hits_per_run = h / r,
         br_a = h + bb + hbp -(.5*ibb) - hr,
         br_b = 1.1 * ((1.4*slg*ab) - (.6*h) - (3*hr) - (.1*(bb+hbp-ibb)) + (.9*(sb-cs-gdp))),
         br_c = pa - bb - sf - sh - hbp - h + cs + gdp,
         br_raw = br_a*br_b/(br_b+br_c)+hr)

br_adjustments <-
  batting_historic %>% 
  group_by(year, league) %>% 
  summarize(r = sum(r),
            br_raw = sum(br_raw)) %>% 
  mutate(adj = r / br_raw) %>% 
  select(-r, -br_raw)

batting_historic <-
  batting_historic %>% 
  left_join(br_adjustments) %>% 
  mutate(base_runs = br_raw * adj * (162/g)) %>% 
  select(-c(br_a:adj))

batting_against_historic <-
  batting_against_historic %>% 
  left_join(br_adjustments) %>% 
  mutate(base_runs = br_raw * adj * (162/g)) %>% 
  select(-c(br_a:adj))
  
batting_results_last_year <-
  batting_historic %>% 
  filter(year == last_year) %>% 
  select(-year) %>% 
  left_join(
    fangraphs_batting_last_year %>% 
      rename(tm = team) %>% 
      select(tm, war)
    )

pitching_results_last_year <-
  batting_against_historic %>% 
  filter(year == last_year) %>% 
  select(-year) %>% 
  left_join(
    fangraphs_pitching_last_year %>%
      rename(tm = team) %>% 
      select(tm, war)
    )

win_total_odds <- 
  win_total_odds_raw %>% 
  tidyr::separate_rows(o_u_wins_this_year, sep = " ") %>% 
  filter(o_u_wins_this_year != "Wins") %>% 
  mutate(o_u_wins_this_year = as.numeric(o_u_wins_this_year)) %>% 
  left_join(team_abbreviation_map) %>% 
  select(tm, o_u_wins_this_year)

```

Step 1 - Get Data

```{r Step 1}

team_stats_last_year <-
  standings_last_year %>% 
  select(-r_g, -g) %>% 
  left_join(
    (batting_results_last_year %>% 
       select(-league)), by = c("tm")) %>% 
left_join(
  (pitching_results_last_year %>% 
  rename_with(~paste0(., "_a"), ra_g:base_runs)),
  by = c("tm")) %>%
  rename(r_last_year = r,
         ra_last_year = r_a) %>% 
  mutate(r_this_year = (r_last_year * games_this_year / g) %>% round(2),
         ra_this_year = (ra_last_year * games_this_year / g) %>% round(2))
  
step1 <-
  team_stats_last_year %>% 
  select(tm, r_this_year, ra_this_year) %>% 
  rename(r = r_this_year,
         ra = ra_this_year)

step1 %>% 
  write_csv(here::here("out", "step1.csv"))

team_projections_this_year <- step1
```

Step 2: Calculate each team's cluster luck adjustments

```{r Step 2}

hpr_model <- 
  batting_historic %>% 
  lm(hits_per_run ~ obp + slg + iso, .)

intercept_coefficient <- hpr_model$coefficients[[1]]
obp_coefficient <- hpr_model$coefficients[[2]]
slg_coefficient <- hpr_model$coefficients[[3]]
iso_coefficient <- hpr_model$coefficients[[4]]

team_stats_last_year <-
  team_stats_last_year %>% 
  mutate(hits_per_run = 
           (iso_coefficient * iso) +
           (slg_coefficient * slg) +
           (obp_coefficient * obp) +
           intercept_coefficient,
         hits_a_per_run = 
           (iso_coefficient * iso_a) +
           (slg_coefficient * slg_a) +
           (obp_coefficient * obp_a) +
           intercept_coefficient,
         runs_exp = (h / hits_per_run + base_runs)/2,
         runs_a_exp = (h_a / hits_a_per_run + base_runs)/2)

step2 <-
  team_stats_last_year %>% 
  mutate(
    # positive value means they were unlucky (runs were expected higher)    
    r = ((runs_exp - r_last_year) * (games_this_year / g)) %>% round(2), 
    # positive value means they were unlucky (runs allowed were expected lower)    
    ra = ((ra_last_year - runs_a_exp) * (games_this_year / g)) %>% round(2)) %>%
  select(tm, r, ra) 

step2 %>% 
  write_csv(here::here("out", "step2.csv"))

team_projections_this_year <- 
  apply_adjustments(team_projections_this_year, step2)

```

Step 3: Calculate team offense and pitching WAR adjustments

```{r Step 3}

adjust_war <- function(last_year_results, 
                       this_year_projections) {
  team_projections_this_year %>% 
    rename(r_running_adj = r, 
           ra_running_adj = ra) %>% 
    left_join(team_stats_last_year, by = "tm") %>% 
    left_join(this_year_projections, by = "tm") %>% 
    left_join(last_year_results, 
              by = "tm", 
              suffix = c("_proj","")) %>% 
    mutate(war_adj = (war * games_this_year / g) %>% round(2),
           war_diff = war_proj - war_adj,
           wp_diff = war_diff / games_this_year,
           pyth_old = r_running_adj^ex / 
             (r_running_adj^ex + ra_running_adj^ex),
           r_exponent = ra_running_adj^ex * (wp_diff + pyth_old) /
             (1 - (wp_diff + pyth_old)),
           ra_exponent = 
             r_running_adj^ex * (1 - wp_diff - pyth_old) / 
             (wp_diff + pyth_old),
           r = (r_exponent^(1/ex) - r_running_adj) %>% round(2),
           ra = (ra_exponent^(1/ex) - ra_running_adj) %>% round(2))
}

step3a <-
  adjust_war(batting_results_last_year, batting_projections_this_year)
  
step3b <-
  adjust_war(pitching_results_last_year, pitching_projections_this_year)
  
step3 <- 
  step3a %>%
  full_join(step3b, by = "tm", suffix = c(".a", ".b")) %>% 
  select(tm, r.a, ra.b) %>% 
  rename(r = r.a,
         ra = ra.b)
    
step3a %>% write_csv(here::here("out", "step3a.csv"))
step3b %>% write_csv(here::here("out", "step3b.csv"))
step3 %>% write_csv(here::here("out", "step3.csv"))

team_projections_this_year <- 
  apply_adjustments(team_projections_this_year, step3)

```

Step 4: Sum up adjustments

```{r Step 4}

team_projections_this_year %>% 
  write_csv(here::here("out", "step4.csv"))

```

Step 5: Normalize all RS/RA to last year's environment of total runs

```{r Step 5}
# add the correct number of runs/allowed to each team so that the total projected for this year equals the last year's 162 game page

runs_projected_this_year <- 
  team_projections_this_year %>% 
  summarize(r = sum(r),
            ra = sum(ra)) %>% 
  mutate(year = this_year)

runs_pace_last_year <-
  #how many runs would be scored by all teams in 162 games
  team_stats_last_year %>% 
  select(tm, g, r_last_year:ra_this_year) %>% 
  mutate(r_last_year_162 = r_last_year * games_this_year / g,
         ra_last_year_162 = ra_last_year * games_this_year / g) %>% 
  summarize(across(r_last_year_162:ra_last_year_162, sum)) %>% 
  rename(r = r_last_year_162,
         ra = ra_last_year_162) %>% 
  mutate(year = last_year)

team_count <- 
  team_stats_last_year %>% 
  summarize(n = n()) %>% 
  pull()
  
runs_projected_adjustments <-
  tibble(r = (runs_pace_last_year$r - runs_projected_this_year$r) / team_count, 
         #total runs (per team) scored last year minus this year
         ra = (runs_pace_last_year$ra - runs_projected_this_year$ra) / team_count)

team_projections_this_year <-
  team_projections_this_year %>% 
  rename(r_raw = r,
         ra_raw = ra) %>% 
  mutate(r = r_raw + runs_projected_adjustments$r, 
         #add (or subtracts) runs to make the "run environments" the same between last year and this year
         ra = ra_raw + runs_projected_adjustments$ra)
```

Step 6: Calculate expected wins via Pythagorean theorem

```{r Step 6}

team_projections_this_year <- 
  team_projections_this_year %>% 
  mutate(r_last_year_adj = step3a$r_this_year + runs_projected_adjustments$r,
         ra_last_year_adj = step3b$ra_this_year + runs_projected_adjustments$ra,
         r_adjustment = r - r_last_year_adj,
         ra_adjustment = ra - ra_last_year_adj,
         r_diff = r - ra,
         r_g = r / games_this_year,
         ra_g = ra / games_this_year,
         wp = r^ex / (r^ex + ra^ex)) %>% 
  select(tm, wp, r, ra, r_last_year_adj, ra_last_year_adj, r_adjustment, ra_adjustment, r_diff, r_g, ra_g)

team_projections_this_year %>% 
  arrange(wp %>% desc()) %>% 
  mutate_if(is.numeric, ~round(., 3)) %>% 
  write_csv(here::here("out", "step5.csv"))
```

```{r Compare to Fangraphs}

projection_comparison <-
  team_projections_this_year %>% 
  left_join(fangraphs_projections, 
            by = "tm", 
            suffix = c("_us", "_fangraphs")) %>% 
  rename(w_fangraphs = w) %>% 
    mutate(w_us = (games_this_year * wp_us) %>% round)

wins_proj_plot <-
  projection_comparison %>% 
    select(tm, w_fangraphs, w_us) %>% 
    ggplot(aes(w_fangraphs, w_us, color=tm)) +
    geom_point() +
    geom_abline(slope=1)

ggplotly(wins_proj_plot)

```

```{r Compare to Vegas}

odds_comparison <-
  projection_comparison %>% 
  left_join(win_total_odds) %>% 
  select(tm, w_us, o_u_wins_this_year) %>% 
  distinct() %>% 
  mutate(diff = w_us - o_u_wins_this_year)

odds_comparison %>% 
  ggplot(aes(diff)) +
  geom_histogram(binwidth = 4)

odds_comparison %>% 
  filter(abs(diff) > 4) %>% 
  arrange(abs(diff) %>% desc) %>% 
  write_csv(here::here("out", "potential_bets.csv"))
  
```
